# Basic `numpy`

`numpy` is a python package that is a real workhorse of machine learning and data science.

If you're new to python, this will be the first true package you'll import. That being said we should check that you have the package installed, try to run the following code chunk. (Note if you installed the Anaconda platform, <a href="https://www.anaconda.com/">https://www.anaconda.com/</a>, `numpy` should be installed already).

In [1]:
## it is standard to import numpy as np
import numpy as np

In [2]:
## let's check what version of numpy you have
## when I wrote this I had version 1.20.1
## yours may be different
print(np.__version__)

1.20.1


If you had a version of `numpy` installed, both of those code chunks should have run fine for you. If not, you will need to install it onto your machine because we will be using it heavily in the boot camp. For installation instructions check out the `numpy` documentation here, <a href="https://numpy.org/install/">https://numpy.org/install/</a>. 

##### Be sure to install the package and rerun the above code chunks before continuing.

## `numpy`'s ndarray

While base python likes to store data in objects like `list`s and `tuple`s, in `numpy` data is stored in an `ndarray` it is similar to a list, but has a number of features that make it more useful for numeric data manipulation in a number of data science applications.

In [3]:
## You can make an array with np.array
## You just put np.array() around a python list or tuple
array1 = np.array([1,2,3,4])
print(array1)
print()
print(type(array1))

[1 2 3 4]

<class 'numpy.ndarray'>


`numpy` `ndarray`s can have any finite number of dimensions. This can be constructed by wrapping `np.array` around a `list` of `list`s.

In [4]:
## this produces a 2-dimensional array
## it is a 2x2 array
array2 = np.array([[1,2],[2,1]])
print(array2)
print()

## we can check the array's dimensions with np.shape()
## np.shape() returns a tuple with the size of each dimension
## array2 should be a 2 by 2 array
print("array2 is a",np.shape(array2),"ndarray")

[[1 2]
 [2 1]]

array2 is a (2, 2) ndarray


In [5]:
## You code
## Try making a 2x2x2 array



In [6]:
## You code 
## Try making a 2x2x2x2 array



### `ndarray` Functions

#### Vectorized Operations

`ndarray`s are nice because, for the most part, they work the way you'd expect a vector or matrix to work. Let's compare and contrast with python's `list`s.

In [7]:
## You code
## see what happens when you code up 2*list1
list1 = [1,2,3,4]



In [8]:
## You code
## Now compare it to 2*array1


In [9]:
## You code
## what happens here
[1,2] + [3,4]

[1, 2, 3, 4]

In [10]:
## You code
## code up the comparable ndarray expression
## and see what happens


In [11]:
## You code
## Finally what happens here?
y = 3*[1,2,3] + 2

TypeError: can only concatenate list (not "int") to list

In [12]:
## You code
## try the comparable ndarray expression


### Built-In `numpy` Functions

`numpy` also has a number of built-in functions that provide useful mathematical operations on arrays. Let's look at some examples.

In [13]:
y = 2*np.array([1,2,3]) - 4
print(y)

[-2  0  2]


In [14]:
## absolute value
np.abs(y)

array([2, 0, 2])

In [15]:
## raising each entry to a power
np.power(y,3)

array([-8,  0,  8])

In [16]:
## the square root
np.sqrt(np.abs(y))

array([1.41421356, 0.        , 1.41421356])

In [17]:
## You code
## using np.exp define y to be 
## e^(x+3) + log(|x|+1)
## https://numpy.org/doc/stable/reference/generated/numpy.exp.html
x = np.array([0,1,2,3,4])




In [18]:
## You can sum all of the entries of an array with
## np.sum
np.sum(y)

0

### Preset `numpy` Arrays

There are a number of standard array types that you'll want to use, that can be quickly generated.

In [19]:
## np.ones(shape) makes an array of all ones of the desired shape
print(np.ones(1))

print()

print(np.ones((4,10)))

print()

print(np.ones((2,2,2)))

[1.]

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [20]:
## You code
## np.zeros(shape) is similar to np.ones, but instead of 1s
## it makes an array of 0s
## print 3 arrays of zeros, 
## one that is a single dimension of size 4


## one that is 2x17

## one that is 3x3x2x2

## `numpy` for Pseudorandomness

`numpy` is useful for generating pseudorandom numbers as well. We can look at common statistics of arrays too.

The pseudorandom functionality is stored in the `random` subpackage of `numpy`.

In [21]:
## random generators are stored in np.random
## a np.random.random() gives a number selected uniformly
## at random from [0,1]
print(np.random.random())


print()

## You can get a random array of any shape as well
print("A (10,2) uniform random array:\n", np.random.random((10,2)))

0.9602253041987722

A (10,2) uniform random array:
 [[0.82139576 0.93830152]
 [0.73710631 0.2526835 ]
 [0.84319483 0.96738036]
 [0.9333189  0.07368613]
 [0.40832009 0.93663353]
 [0.040357   0.32148958]
 [0.9221872  0.18512686]
 [0.47205732 0.92539945]
 [0.55460805 0.70426077]
 [0.47410278 0.03902226]]


In [22]:
## Another Example
## np.random.randn() is a normal(0,1) number
## a single draw
print(np.random.randn())
print()

## an array of draws
## note the slight difference here, we don't have to put
## the 10 and 2 in a tuple to get a 10 by 2 array
## numpy is slightly inconsistent in this area so always
## check the docs to get it right
np.random.randn(10,2)

1.0505422381037393



array([[-1.27172066, -0.51268849],
       [ 0.64999015, -0.08578567],
       [ 0.75977635, -1.33362643],
       [-0.97899603, -0.02495833],
       [ 1.06250273,  0.258612  ],
       [ 0.9148927 , -1.48317419],
       [ 1.67881129,  0.71401383],
       [-1.68332626, -0.44863374],
       [ 0.42171053,  0.84888552],
       [-1.30691977, -3.00263034]])

In [23]:
## A third example
## np.random.binomial()
## an array of binomial(n,p) outcomes
np.random.binomial(n=4, p=.3, size=(10,10))

array([[0, 1, 2, 1, 3, 0, 2, 2, 1, 0],
       [3, 2, 2, 1, 1, 1, 1, 2, 1, 3],
       [1, 1, 1, 2, 1, 3, 1, 1, 0, 1],
       [1, 0, 1, 3, 2, 2, 3, 0, 1, 0],
       [2, 3, 1, 2, 1, 1, 0, 2, 1, 1],
       [1, 2, 2, 2, 1, 0, 2, 0, 2, 1],
       [2, 2, 0, 1, 1, 2, 0, 2, 1, 3],
       [1, 1, 2, 1, 0, 1, 3, 1, 1, 1],
       [1, 0, 2, 2, 1, 2, 0, 0, 0, 2],
       [3, 0, 2, 1, 2, 1, 2, 3, 1, 1]])

In [24]:
## You code
## make a 20 by 3 array of random normal draws
## call it X


Now that you have a data matrix, `X`. Let's compute some summary statistics about `X`.

In [25]:
## You can get the mean of all the entries of X with np.mean
print("The overall mean of X is", np.mean(X))
print()

## Adding in the argument "axis = " allows you to get
## the mean of each column
print("The column means of X are", np.mean(X, axis=0))
print()

## and the mean of each row
print("The row means of X are", np.mean(X, axis=1))
print()

## the axis argument tells numpy the axis or axes along 
## which the means are computed.
## so axis = 0 adds up the values in each row position
## and divides by the number of rows

## If you find this confusing, don't worry, I do too

The overall mean of X is 0.05995646966466975

The column means of X are [-0.07462103  0.05456334  0.1999271 ]

The row means of X are [ 0.59129083 -0.77202112 -0.64818489  0.34715777  0.93320465  0.34108929
 -0.07681477  1.02091719 -0.59216068  0.38785023 -0.04493173  0.88377311
  0.87916706 -0.55216546 -0.39302604 -0.854961   -0.39241663  0.10646032
 -0.22576981  0.26067109]



In [26]:
## You code
## np.sum also has an axis argument
## calculate the row sums and column sums of X





Other common functions are `np.std()` for standard deviation, `np.var()` for variance, `np.min()` for min, `np.max()` for max, `np.argmin()` for where the min occurs, `np.argmax()` for where the max occurs.

In [27]:
## You code
## where does the max value occur in each column of X?



## what is the max value in each column of X?


In [28]:
## Another useful function is np.cumsum()

## randint generates a random integer between the
## first two arguments, the third argument tells numpy
## how many random draws to perform
x = np.random.randint(1,10,10)

print(x)

np.cumsum(x)

## What do you think it does?

[4 2 2 9 5 3 8 6 9 2]


array([ 4,  6,  8, 17, 22, 25, 33, 39, 48, 50])

## Linear Algebra with `numpy`

A final important use for us is `numpy` as a way to perform linear algebra calculations.

A bulk of data science algorithms use linear algebra, since we'll dive into the math behind the scenes of these algorithms we'll use `numpy`'s linear algebra capabilities.

##### Note: If you're not a math heavy person, that's okay! I have written the boot camp's notebooks so that you don't need to understand the math to learn how to perform the algorithms we cover. I just like to cover the mathematical aspects of these data science algorithms to explain what is going on to those boot campers (like myself) that are interested in the mathematical/statistical underpinnings of the algorithms.

In [40]:
## We can think of a 2D array as a matrix
A = np.random.binomial(n=10,p=.4,size=(2,2))

A

array([[3, 5],
       [6, 2]])

In [30]:
## A 1d array can be a row vector
x = np.array([1,2])
x

array([1, 2])

In [31]:
## or a column vector
## reshape() will attempt to reshape your array into the given
## shape

## When one of the shape dimensions is -1, the value is inferred from 
## the length of the array and remaining dimensions.
## so -1,1 tells numpy that you want a 2-D array with 1 column
## and it should infer the number of rows from the original shape
## of the array
## Here this reshapes x as a 2x1 column vector
x.reshape(-1,1)

array([[1],
       [2]])

In [32]:
## We can now calculate A*x
## matrix.dot() is used for matrix mult
A.dot(x.reshape(-1,1))

array([[3],
       [6]])

In [33]:
## You code
## make a 3-D column vector of ones, call it x


## Take that vector and find B*x
B = np.random.binomial(n=5, p=.6, size=(3,3))




In [34]:
## numpy.linalg contains a number of useful
## matrix operations, let's import a few
from numpy.linalg import inv, eig, det

In [41]:
## the inverse of A
## Note you may get an error here if A is not
## invertible
inv(A)

array([[-0.08333333,  0.20833333],
       [ 0.25      , -0.125     ]])

In [42]:
## the determinant of A
det(A)

-23.999999999999993

In [44]:
## the eigenvalues and eigenvectors of A
eig(A)

## this returns a tuple of arrays
## the first entry are the eigenvalues
## the second entry are the corresponding eigenvectors

(array([ 8., -3.]), array([[ 0.70710678, -0.6401844 ],
        [ 0.70710678,  0.76822128]]))

In [45]:
## matrix.transpose() computes the transpose of the matrix
A.transpose()

array([[3, 6],
       [5, 2]])

In [ ]:
## You code
b = np.array([2,5]).reshape(-1,1)

## Attempt to solve Ax = b for x
## Hint remember that if A is invertible, 
## x = A^{-1} b, where A^{-1} is the inverse of A



## That's it!

That's it for this notebook. You have now been introduced to `numpy` and our ready to take on the practice problems. Be sure to get a fair level of comfort with `numpy`'s functionality because we'll be using it a lot.