# `numpy`

These problems go along with the material presented in the `Basic Numpy` notebook in the python prep folder.

## Basic Problems

1. Import `numpy` and check your version.

2. Create an array from $-10$ to $10$ with steps of $1$ using `np.arange`. Hint: If you don't know how `np.arange` works search for it on the web.

3. Create an array from $-10$ to $10$ with $1000$ evenly spaced steps using `np.linspace`.

4. Use `numpy`'s `random` subpackage (accessed using `np.random`) to generate a random draw from $[0,1]$.

5. Use `numpy`'s `random` to make a random array of length 20 and store it in a variable called `x`.  Run `x > .2`, what comes out? Then try `x[x >.2]`, what happens?

In [1]:
## 1. ANSWER
import numpy as np

print(np.__version__)


1.20.1


In [2]:
## 2. ANSWER

## arange docs, https://numpy.org/doc/stable/reference/generated/numpy.arange.html
np.arange(-10,11,1)




array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10])

In [3]:
## 3. ANSWER

## linspace docs, https://numpy.org/doc/stable/reference/generated/numpy.linspace.html

np.linspace(-10,10,100)


array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

In [4]:
## 4. ANSWER

## docs, https://numpy.org/doc/stable/reference/random/generated/numpy.random.random.html
np.random.random()



0.18411843103291092

In [5]:
## 5. ANSWER
## Note you don't need to print out the results, I 
## just did that so I'd only need one code chunk

## make the array
x = np.random.random(20)
print(x)
print()

## check where x > .2
print(x > .2)
print()

## get the values of x where x > .2
print(x[x > .2])



[0.52432048 0.83816151 0.22209934 0.85675271 0.97106182 0.73955874
 0.14916023 0.98479346 0.3015585  0.5686532  0.32217284 0.884321
 0.84149034 0.49097206 0.30949994 0.68404685 0.44482149 0.43132329
 0.52971053 0.39346162]

[ True  True  True  True  True  True False  True  True  True  True  True
  True  True  True  True  True  True  True  True]

[0.52432048 0.83816151 0.22209934 0.85675271 0.97106182 0.73955874
 0.98479346 0.3015585  0.5686532  0.32217284 0.884321   0.84149034
 0.49097206 0.30949994 0.68404685 0.44482149 0.43132329 0.52971053
 0.39346162]


## More Advanced Problems

1. Rewrite your answer to the <i>Random Walk Problem</i> in Practice Problems Notebook 4, no need to write the result to file this time.

2. Write a function that produces a random walk of length $n$ using `numpy`.

In [6]:
## 1. ANSWER

### MAKING THE FLIPS ###
# This is the same as a coin flip
# Tails would be a 0 and 1 would be a Heads
print(np.random.binomial(1,p=.5))
print()

# We can get 100 flips like so
print(np.random.binomial(1,p=.5,size=100))
print()


# flip the coin 100 times
flips = np.random.binomial(1,p=.5,size=100)

# We can map 0,1 to -1,1 using y=2x-1
flips = 2*flips - 1
print(flips)
print()

### GETTING THE POSITONS ###

# initialize the positions array
pos = np.zeros(101)

# use cumsum to get the walk
pos[1:] = np.cumsum(flips)

print(pos)

1

[1 0 1 0 1 1 0 0 0 0 1 0 1 0 1 1 1 1 1 0 1 0 1 0 0 1 1 0 0 1 0 0 0 0 1 1 1
 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 0 0 1 0 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0
 0 1 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 0 1 1 1 1 1 1 1]

[-1  1  1 -1  1 -1 -1 -1 -1  1  1  1  1 -1  1  1  1 -1 -1 -1 -1  1 -1 -1
  1 -1  1 -1  1 -1 -1  1 -1 -1  1 -1 -1 -1  1  1  1 -1  1 -1  1  1  1  1
 -1 -1  1 -1 -1  1 -1  1 -1  1 -1  1 -1 -1 -1  1 -1 -1 -1 -1  1  1  1  1
 -1 -1 -1 -1  1  1 -1  1 -1 -1  1  1  1  1  1 -1 -1 -1 -1  1  1 -1 -1 -1
 -1  1  1  1]

[ 0. -1.  0.  1.  0.  1.  0. -1. -2. -3. -2. -1.  0.  1.  0.  1.  2.  3.
  2.  1.  0. -1.  0. -1. -2. -1. -2. -1. -2. -1. -2. -3. -2. -3. -4. -3.
 -4. -5. -6. -5. -4. -3. -4. -3. -4. -3. -2. -1.  0. -1. -2. -1. -2. -3.
 -2. -3. -2. -3. -2. -3. -2. -3. -4. -5. -4. -5. -6. -7. -8. -7. -6. -5.
 -4. -5. -6. -7. -8. -7. -6. -7. -6. -7. -8. -7. -6. -5. -4. -3. -4. -5.
 -6. -7. -6. -5. -6. -7. -8. -9. -8. -7. -6.]


In [7]:
## 2. ANSWER

# Now we just need to package the above code into a function :)
def random_walk(N):
    # get the flips
    flips = np.random.binomial(1,p=.5,size=N)
    flips = 2*flips - 1

    # Get the positions
    pos = np.zeros(N+1)
    pos[1:] = np.cumsum(flips)
    
    # return the positions
    return pos

In [8]:
# let's print some short walks
for i in range(10):
    print(random_walk(10))
    print()

[0. 1. 0. 1. 2. 1. 2. 1. 0. 1. 2.]

[0. 1. 0. 1. 0. 1. 2. 1. 2. 3. 4.]

[ 0. -1.  0. -1.  0. -1. -2. -3. -2. -1. -2.]

[ 0.  1.  2.  1.  0. -1.  0.  1.  0.  1.  2.]

[ 0. -1. -2. -3. -2. -1. -2. -3. -2. -1.  0.]

[ 0. -1. -2. -1. -2. -1.  0. -1.  0.  1.  2.]

[0. 1. 2. 1. 2. 1. 2. 1. 2. 3. 2.]

[ 0.  1.  0. -1. -2. -3. -4. -3. -2. -1.  0.]

[0. 1. 2. 1. 0. 1. 0. 1. 0. 1. 2.]

[ 0.  1.  0. -1. -2. -3. -4. -3. -2. -3. -2.]



This notebook was written for the Erd&#337;s Institute C&#337;de Data Science Boot Camp by Matthew Osborne, Ph. D., 2021.

Redistribution of the material contained in this repository is conditional on acknowledgement of Matthew Tyler Osborne, Ph.D.'s original authorship and sponsorship of the Erdős Institute as subject to the license (see License.md)